version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
    groups:
      all_dependencies:
         applies-to: version-updates
         patterns:
         - "*"
