#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Ansible Guide documentation build configuration file, created by
# sphinx-quickstart on Tue Sep  6 14:12:35 2016.

extensions = [
    'sphinx.ext.autosectionlabel',
    'adfinis_sphinx_theme'
]

autosectionlabel_prefix_document = True

# General information about the project.
project = 'Ansible Guide'
copyright = 'Adfinis AG'
author = 'Adfinis AG'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '2.0'
# The full version, including alpha/beta/rc tags.
release = '2.0'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'
